# Generated by Django 6.0 on 2026-04-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='grade_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
