# Generated by Django 6.0 on 2026-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teachersmessage_created_at_remove_grades_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
