# Generated by Django 6.0 on 2026-05-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_grades_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='age',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='photo',
        ),
    ]
