# Generated by Django 6.0 on 2026-05-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_parents_age_remove_parents_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='grades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.grades'),
        ),
    ]
