# Generated by Django 6.0 on 2026-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_sex_students_gender_students_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.CharField(max_length=10000),
        ),
    ]
