# Generated by Django 6.0 on 2026-05-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_students_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(upload_to='Students_photo'),
        ),
    ]
