# Generated by Django 6.0 on 2026-05-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_students_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Test', 'Test'), ('Class Activity', 'Class Activity'), ('Mid Examination', 'Mid Examination'), ('Final Examination', 'Final Examination'), ('Assignment', 'Assignment')], max_length=100)),
                ('out_of', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveIntegerField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_list', to='core.grades')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.students')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Permission', 'Permission')], max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.grades')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.students')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'classes', 'date')},
            },
        ),
    ]
