# Generated by Django 6.0 on 2026-05-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_marklist_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marklist',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='marklist',
            unique_together={('student', 'category')},
        ),
    ]
