# Generated by Django 6.0 on 2026-05-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_marklist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marklist',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='marklist',
            unique_together=set(),
        ),
    ]
