# Generated by Django 6.0 on 2026-06-27 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_marklist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_and_assignments', models.PositiveIntegerField()),
                ('attendance_class_activity_mark', models.PositiveIntegerField()),
                ('exercise_book_mark', models.PositiveIntegerField()),
                ('mid_final_mark', models.PositiveIntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.grades')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.students')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.semesters')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.ForeignKey(default='First Semester', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.semesters'),
        ),
        migrations.AddField(
            model_name='marklist',
            name='semester',
            field=models.ForeignKey(default='First Semester', on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.semesters'),
        ),
    ]
