# Generated by Django 6.0 on 2026-06-27 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_semesters_reportcard_attendance_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.semesters'),
        ),
    ]
