# Generated by Django 6.0 on 2026-06-27 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_attendance_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='semester',
        ),
    ]
