# Generated by Django 6.0 on 2026-06-27 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_attendance_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.ForeignKey(default='First Semester', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.semesters'),
        ),
    ]
