# Generated by Django 6.0 on 2026-06-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_attendance_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='attendance_class_activity_mark',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='exercise_book_mark',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='mid_final_mark',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.semesters'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='test_and_assignments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
