# Generated by Django 6.0 on 2026-06-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_reportcard_attendance_class_activity_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='average_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
