# Generated by Django 6.0 on 2026-06-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reportcard_average_mark_reportcard_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marklist',
            name='category',
            field=models.CharField(choices=[('Test', 'Test'), ('Exercise Book', 'Exercise Book'), ('Class Activity', 'Class Activity'), ('Mid Examination', 'Mid Examination'), ('Final Examination', 'Final Examination'), ('Assignment', 'Assignment')], max_length=100),
        ),
    ]
