# Generated by Django 6.0 on 2026-06-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_marklist_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcard',
            options={'ordering': ['-average_mark']},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'grade')},
        ),
    ]
