# Generated by Django 6.0 on 2026-06-28 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bible_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_lesson', to=settings.AUTH_USER_MODEL)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
                ('memory_verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_verse', to=settings.AUTH_USER_MODEL)),
                ('program_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_leader', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
